apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: cd-pipeline-run-
spec:
  pipelineRef:
    name: cd-pipeline
  params:
    - name: repo-url
      value: https://github.com/muhammadbilaldevops/IBM-DevOps-Capstone-Project.git
    - name: revision
      value: main
    - name: build-image
      value: accounts:latest
  workspaces:
    - name: pipeline-workspace
      emptyDir: {}
